trigger:
- main

pool:
  name: 'Default'

steps:
- script: terraform init
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Terraform Init'
  env:
    TF_VAR_subscription_id: $(TF_VAR_subscription_id)
    TF_VAR_tenant_id:       $(TF_VAR_tenant_id)
    TF_VAR_client_id:       $(TF_VAR_client_id)
    TF_VAR_client_secret:   $(TF_VAR_client_secret)
    TF_VAR_storage_account_name: $(TF_VAR_storage_account_name)
    TF_VAR_location:        $(TF_VAR_location)
    TF_VAR_resource_group_name: $(TF_VAR_resource_group_name)
    TF_VAR_allowed_source_ips: $(TF_VAR_allowed_source_ips)
    TF_VAR_allowed_ip_range_start: $(TF_VAR_allowed_ip_range_start)
    TF_VAR_allowed_ip_range_end: $(TF_VAR_allowed_ip_range_end)
    TF_VAR_vm_admin_username: $(TF_VAR_vm_admin_username)
    TF_VAR_sql_admin_username: $(TF_VAR_sql_admin_username)
    TF_VAR_admin_ssh_public_key: $(TF_VAR_admin_ssh_public_key)
    TF_VAR_key_vault_name: $(TF_VAR_key_vault_name)
    TF_VAR_key_vault_rg: $(TF_VAR_key_vault_rg)
    TF_VAR_sql_admin_password_secret_name: $(TF_VAR_sql_admin_password_secret_name)
    TF_VAR_vm_ssh_private_key_secret_name: $(TF_VAR_vm_ssh_private_key_secret_name)
    TF_VAR_ssl_certificate_secret_name: $(TF_VAR_ssl_certificate_secret_name)
    TF_VAR_domain_name: $(TF_VAR_domain_name)

- script: terraform plan -out=tfplan
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Terraform Plan'
  env:  # same as above
    TF_VAR_subscription_id: $(TF_VAR_subscription_id)
    TF_VAR_tenant_id:       $(TF_VAR_tenant_id)
    TF_VAR_client_id:       $(TF_VAR_client_id)
    TF_VAR_client_secret:   $(TF_VAR_client_secret)
    TF_VAR_storage_account_name: $(TF_VAR_storage_account_name)
    TF_VAR_location:        $(TF_VAR_location)
    TF_VAR_resource_group_name: $(TF_VAR_resource_group_name)
    TF_VAR_allowed_source_ips: $(TF_VAR_allowed_source_ips)
    TF_VAR_allowed_ip_range_start: $(TF_VAR_allowed_ip_range_start)
    TF_VAR_allowed_ip_range_end: $(TF_VAR_allowed_ip_range_end)
    TF_VAR_vm_admin_username: $(TF_VAR_vm_admin_username)
    TF_VAR_sql_admin_username: $(TF_VAR_sql_admin_username)
    TF_VAR_admin_ssh_public_key: $(TF_VAR_admin_ssh_public_key)
    TF_VAR_key_vault_name: $(TF_VAR_key_vault_name)
    TF_VAR_key_vault_rg: $(TF_VAR_key_vault_rg)
    TF_VAR_sql_admin_password_secret_name: $(TF_VAR_sql_admin_password_secret_name)
    TF_VAR_vm_ssh_private_key_secret_name: $(TF_VAR_vm_ssh_private_key_secret_name)
    TF_VAR_ssl_certificate_secret_name: $(TF_VAR_ssl_certificate_secret_name)
    TF_VAR_domain_name: $(TF_VAR_domain_name)

- script: terraform apply -auto-approve tfplan
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Terraform Apply'
  env:  # same as above
    TF_VAR_subscription_id: $(TF_VAR_subscription_id)
    TF_VAR_tenant_id:       $(TF_VAR_tenant_id)
    TF_VAR_client_id:       $(TF_VAR_client_id)
    TF_VAR_client_secret:   $(TF_VAR_client_secret)
    TF_VAR_storage_account_name: $(TF_VAR_storage_account_name)
    TF_VAR_location:        $(TF_VAR_location)
    TF_VAR_resource_group_name: $(TF_VAR_resource_group_name)
    TF_VAR_allowed_source_ips: $(TF_VAR_allowed_source_ips)
    TF_VAR_allowed_ip_range_start: $(TF_VAR_allowed_ip_range_start)
    TF_VAR_allowed_ip_range_end: $(TF_VAR_allowed_ip_range_end)
    TF_VAR_vm_admin_username: $(TF_VAR_vm_admin_username)
    TF_VAR_sql_admin_username: $(TF_VAR_sql_admin_username)
    TF_VAR_admin_ssh_public_key: $(TF_VAR_admin_ssh_public_key)
    TF_VAR_key_vault_name: $(TF_VAR_key_vault_name)
    TF_VAR_key_vault_rg: $(TF_VAR_key_vault_rg)
    TF_VAR_sql_admin_password_secret_name: $(TF_VAR_sql_admin_password_secret_name)
    TF_VAR_vm_ssh_private_key_secret_name: $(TF_VAR_vm_ssh_private_key_secret_name)
    TF_VAR_ssl_certificate_secret_name: $(TF_VAR_ssl_certificate_secret_name)
    TF_VAR_domain_name: $(TF_VAR_domain_name)