trigger:
- main

pool:
  name: 'Default'

steps:

- script: terraform --version
  displayName: 'Verify Terraform CLI'

- script: az --version
  displayName: 'Verify Azure CLI'

- script: terraform init
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Terraform Init'
  env:
    ARM_SUBSCRIPTION_ID: $(subscription_id)
    ARM_CLIENT_ID: $(client_id)
    ARM_CLIENT_SECRET: $(client_secret)
    ARM_TENANT_ID: $(tenant_id)

- script: terraform plan -out=tfplan
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Terraform Plan'
  env:
    ARM_SUBSCRIPTION_ID: $(subscription_id)
    ARM_CLIENT_ID: $(client_id)
    ARM_CLIENT_SECRET: $(client_secret)
    ARM_TENANT_ID: $(tenant_id)

- script: terraform apply -auto-approve tfplan
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Terraform Apply'
  env:
    ARM_SUBSCRIPTION_ID: $(subscription_id)
    ARM_CLIENT_ID: $(client_id)
    ARM_CLIENT_SECRET: $(client_secret)
    ARM_TENANT_ID: $(tenant_id)