trigger:
- main

pool:
  name: 'Default'

variables:
  - name: subscription_id
    value: $(subscription_id)
  - name: client_id
    value: $(client_id)
  - name: client_secret
    value: $(client_secret)
  - name: tenant_id
    value: $(tenant_id)

steps:

- script: terraform init
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Terraform Init'
  env:
    ARM_SUBSCRIPTION_ID: $(subscription_id)
    ARM_CLIENT_ID: $(client_id)
    ARM_CLIENT_SECRET: $(client_secret)
    ARM_TENANT_ID: $(tenant_id)

- script: terraform plan -out=tfplan
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Terraform Plan'
  env:
    ARM_SUBSCRIPTION_ID: $(subscription_id)
    ARM_CLIENT_ID: $(client_id)
    ARM_CLIENT_SECRET: $(client_secret)
    ARM_TENANT_ID: $(tenant_id)

- script: terraform apply -auto-approve tfplan
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Terraform Apply'
  env:
    ARM_SUBSCRIPTION_ID: $(subscription_id)
    ARM_CLIENT_ID: $(client_id)
    ARM_CLIENT_SECRET: $(client_secret)
    ARM_TENANT_ID: $(tenant_id)